# Generated by Django 2.2.7 on 2019-11-26 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_auto_20191124_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to=settings.AUTH_USER_MODEL),
        ),
    ]
