# Generated by Django 2.2.7 on 2019-11-28 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
