# Generated by Django 2.2.7 on 2019-11-28 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "current_location",
                    models.CharField(default="pending", max_length=50),
                ),
                (
                    "tracking_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "booking_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booked_cargo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_cargo",
                        to="branches.Branch",
                    ),
                ),
                (
                    "clearing_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleared_cargo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargo_received",
                        to="branches.Branch",
                    ),
                ),
                (
                    "recepient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_cargo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_cargo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
