# Generated by Django 2.2.7 on 2019-11-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='tracking_id',
        ),
    ]
